apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-python-app
  template:
    metadata:
      labels:
        app: my-python-app
    specs:
      containers:
      - name: my-python-app
        image:
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: my-python-app-svc
spec:
  selector:
    app: my-python-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000